sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '4'
before_install:
- npm i -g npm@^2.0.0
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm prune
after_success:
- npm run report-coverage
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: PWJVRlgTKB43s6stosHoag153Rr9pAWR1Z0bmPDXqKoNbIMPrmZieiOzncD1XYSfI0Js0yUCHq0WmXvmDBqkWyyaKGkLaEq5qeInx0e67aQWQD6C6DrHfx5L9TA8h/hydeZKH3rW9d+daaOBzR0CQSKvCbLhLplHokerTBsEWnRqvENL4Nb9ERybZG2VPDNdq9ziTjT1e1b4cZO50NllnKztuj6k4ipX4KSCrTV60OK6YBzKLooi2umoUmk+sqgG734KLslMI88jxxDxa3HxOvlqgBH1/ny7LY7fVa8RzHB9WfRS4X8ADpUyf6mn/kL6tvpyulYcb8RScx4sbaiWefNkUrb7HUsXLCuEJHKWWoXImf9kKQXcevhaTUsSFY6rGmnUj9QLNOQXKBgGs0NU0j8KeyufrFSdcofLz+U/bo1EGLYjXtcL1+lrUo4RP/OFZCLa7EhgsyUosZpWRHsKcygyMHXouZLH0iqzzsQQq2FjXWtjN5AhKEkG4wMgQZArdeAzU4u1ygZJ8giU2DJhC8yXQP9+lihI8q7cQzqwoex0QpHl3jzz4S92Ody4x+EpeGbEX8QgXHaf7oYa0/nL2iHX/3tzaDDRoa1pgF87vWLbLQdfcxJklxoYXZ88gGhkdx4Ysz5COge0oPNCAWBliz4jETR3QFoSGrSUB1V3RlI=
  - secure: biZF96THGavtFcPrWoSagRz1FvGkb+Ync68H67IORyEsuG06U6TDutO9vjoOLn9aOUd5Zfc5GLtcTypSXVwa7GvgtERkRKKmk3qxS5P7ETgsDcfNB8jxnYejO1r6pryFXm1lVt5ag5MJ5oc70q24ZrEHurMkQaPJADnqkeZxokbv90mCOXAqytLMEqf84rgn74hvgHGx3o4lnEGnm5IBcVOt1jnzjXKgVeBIk6+oLY7QX0ntz3tyPjG+AgRdD1eGo1FW98Hrj+Xh7dDkMxhg1Z8UFAxU3f9a0tT9OyRyteZdv/gPvw/SxUJxcyHvE4bxgeJd486GkYf4/MjlFFg0iBC5ZXzN05YjhgT6UKfkEp3sRGNSB2eHaDndvU05hediQFsJQWDpj1mspaTsIXyN9eMaYjTl3+ImB0rybwWbfYelueSWyHI9ssiitz8ZK0OgfwDEuNiDZ/3GSQAn6WBmCUrHT3EDhjJu8wYq7BuCZGav0iEMoKRGSz+tsX4Sd8oqnfE3VYULjRUy8ektN7OsP1hFxFUmpG7OuKN+abDoQOcr79lHaJEpHQ9/YKxiqhXjnBIyWSScfRnSqje7hsUnDAU01IDXWjr2l1SZ8wZch4ec8zd1eA6Xlolff1qq4ENZNLECPA5uehlw8JpnF1TPoS/AENUyPCufsBx5p0nl5Jw=
