sudo: false
language: node_js
cache:
  directories:
  - node_modules
notifications:
  email: false
node_js:
- '4'
before_install:
- npm i -g npm@^2.0.0
- export CHROME_BIN=chromium-browser
- export DISPLAY=:99.0
- sh -e /etc/init.d/xvfb start
before_script:
- npm prune
after_success:
- npm run report-coverage
- npm run semantic-release
branches:
  except:
  - "/^v\\d+\\.\\d+\\.\\d+$/"
env:
  global:
  - secure: nNlKMpi2YY7RFXpDTwxhVybFrsV4laalTC5EEE/sZcmJL4bwSs/Z00U1+6NAMjXA3PSZAxMeZ5MrFU1B4+vaSP8aPIveVNpt5hiInJ32siuBIcsFJdWSaz52btJm0o9lK11G1EnFDaz3y6Asjvqb1bQp2CP+NBHFpWzC1VsWZ8f579tJgm4IHYURcDJsPZumd7qQllWLhdh26W3DGtsTApa5F/ZhtSHNYNh0Vm9Ehc6RTNhwpI02wROS12pykIdZLkGDN2kRnFgxIyu1yDVKaIpbnCl3AlUjW52DN+kKzmEVj7vV9ImnL6ZGpSOOqcAlAl097h4d9el/4WR+vH6F/Xy+w5cNaK7c6Rc7IHHqQhAoqA7NUl9dohJUwxnJfPvio2HvKVS5jKoRuKb/oEYXTS+RngwNHt9hY3/Fv1VUDBChGasemR5Vkn9kTkrooGBJLlk3m9ZdPyRCVmLv3HxaG7KfYn4bkrXOyTxJokGOOxSGNQ027SpTvuFaN8a6ZVUQm0ktRpocWN49CnMO+z3p+oX/GdGrCV9pQDA6Xh43gOJUELK1OE6n5vMRuIdOcsVM2L7S8aE0fDhO9UeqjNzwIubVCvAo8uvml+WpQWMeJH4NN6u34p0Je47JbwT+lJ37wTBGWADI1UbsrFf1IO8gKoJ4Fjwk5czG22HYpYmYslc=
  - secure: GGYpAGm4W12sD+tW9VClWg2+YfVjJenl9k33hRpYWsfkHZ/wDfCKImx497YT/rSR//wSMUZUgFHTeE8YtOLt01tyiUKE4IGwtWRNFo5A3dpkPFb7Sf/KzM74yqyBwUxcp7m580vx17G30zFO++FZxDnvFbGy57TcwgbTtE343jtTeYSX/1ID8rFoTZcg0lUTNdXbK9gy1GseK5PekwGCXrX9jyNuiO1IaTIoIwQnz9Nmi/9gkr/v+yAv2t+wqDqrT8sOXDsfJ62+rGs2U9gtsm6lZ9+9hGmPLon/Nx99N2buH7R8lkisihboN+grl4dvuDkMl+19vK7+4i72k27Wl5r5zYlwkwX566J8P+NUUqt57r4otL0eOnl9OhPFZuVUAjdMW7vlmpDQghXPSS0jYlsveFKfJejWWe5CR6FLyUh8+TxIyf5t3frxIA6icHKviQyA2ZxKeFG7tawyueeqNeD+k5dM0U/oC6SuIiJGtYkph1B5lPt8/PUnGralm2hi+zV45ZETFNHLKERt0NjFd/EWA6xKqHOyUXgVV9qiuLTUQrKqUaXDkDlwaaSaPyygXArGjau8gziBNQ9bFvvlkT0yArVp3PmGRCwSokvzBQgnzLQMluqFU6VK5SqjCk1eFcMtPjbZHESTENopg33oXeDoZPek0qWwNCF/vQ0IuGg=
