version: "{build}"

environment:
  nodejs_version: "4.2.6"

matrix:
  fast_finish: true

install:
  - choco install firefox
  - choco install googlechrome
  - ps: Install-Product node
  - node --version
  - npm --version
  - npm install

test_script:
  - npm test

build: off